export interface TeamData {
  id: string;
  name: string;
  tag: string;
  captain: string;
  membersCount: number;
  description: string;
  bannerUrl: string;
  logoUrl: string;
  logoText: string;
  platform: 'PS5' | 'PS4' | 'XBOX' | 'PC' | 'CROSSPLAY';
  status: 'ACTIVO' | 'INACTIVO';
  disputando: string;
  palmares: string;
  color: string;
}

export const mockTeamsList: TeamData[] = [
  {
    id: 'team-leguayork',
    name: 'LEGUAYORK ESP',
    tag: 'LYE',
    captain: 'Pancho_T10',
    membersCount: 45,
    description: 'Escuadra competitiva e-sports oficial inscrita en los circuitos de Torneos Pro FC.',
    bannerUrl: '/images/games-background/eafc.jpg',
    logoUrl: '/uploads/equipos/vBHIgHcKxYAGa7eySYtQ_1786465550.webp',
    logoText: 'LY',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Liga Div 1',
    palmares: '3 Títulos',
    color: '#00F0FF',
  },
  {
    id: 'team-sangre-nueva',
    name: 'SANGRE NUEVA FC',
    tag: 'SN FC',
    captain: 'Caxorro_SN',
    membersCount: 21,
    description: 'Sangre Nueva FC nace el 16 de julio de 2022 con una idea clara: construir algo distinto. No solo un equipo, sino una identidad.',
    bannerUrl: '/uploads/equipos/YYBIw10vcqS2QfF9QWVN_1784584698.webp',
    logoUrl: '/uploads/equipos/TcJRrKKYMU0AQcfmRnXN_1784583945.webp',
    logoText: 'SN',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Copa Apertura',
    palmares: '1 Título',
    color: '#EF4444',
  },
  {
    id: 'team-san-lorenzo',
    name: 'SAN LORENZO ESP',
    tag: 'SLE',
    captain: 'SrDeLorean',
    membersCount: 32,
    description: 'Club histórico con amplia trayectoria en torneos internacionales de Clubes Pro y eSports.',
    bannerUrl: '/uploads/equipos/0hCeAuWMmz2WfCVdejcC_1783646086.webp',
    logoUrl: '/uploads/equipos/5DFT7ABBa43ofW3rww0L_1783646061.webp',
    logoText: 'SL',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Liga Div 1',
    palmares: '5 Títulos',
    color: '#10B981',
  },
  {
    id: 'team-papayeros',
    name: 'PAPAYEROS RISING',
    tag: 'RSG',
    captain: 'Papayero_Cap',
    membersCount: 22,
    description: 'Escuadra representativa del norte chileno con gran disciplina táctica.',
    bannerUrl: '/images/games-background/eafc.jpg',
    logoUrl: '/uploads/equipos/FQDibIpHE2a9IYU0DGGd_1784852582.webp',
    logoText: 'RSG',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Liga Div 1',
    palmares: '2 Títulos',
    color: '#FBBF24',
  },
  {
    id: 'team-smart-esports',
    name: 'SMART ESPORTS',
    tag: 'SMT',
    captain: 'Smart_Lead',
    membersCount: 19,
    description: 'Smart Esports Clubes Pro 11 vs 11.',
    bannerUrl: '/images/games-background/eafc.jpg',
    logoUrl: '/uploads/equipos/Fs0g1nG4YysYEsM7rj8H_1782022611.webp',
    logoText: 'SMT',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Liga Ascenso',
    palmares: 'Sin Títulos',
    color: '#38BDF8',
  },
  {
    id: 'team-bsk-esports',
    name: 'BSK ESPORTS',
    tag: 'BSK',
    captain: 'Lucas_BSK',
    membersCount: 28,
    description: 'Club competitivo de alta competencia en torneos Sudamericanos.',
    bannerUrl: '/images/games-background/eafc.jpg',
    logoUrl: '/uploads/equipos/WhpHJ3BY3t4c1b4CKq64_1783646037.webp',
    logoText: 'BSK',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Liga Div 1',
    palmares: '4 Títulos',
    color: '#A855F7',
  },
  {
    id: 'team-audax-esports',
    name: 'AUDAX ESPORTS',
    tag: 'AUD',
    captain: 'Matias_AUD',
    membersCount: 26,
    description: 'Rama de deportes electrónicos del histórico club itálico.',
    bannerUrl: '/images/games-background/eafc.jpg',
    logoUrl: '/uploads/equipos/Khr6no1kZ2HzUcyLYwyT_1783646344.webp',
    logoText: 'AUD',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Liga Div 1',
    palmares: '1 Título',
    color: '#059669',
  },
  {
    id: 'team-urban-knights',
    name: 'URBAN KNIGHTS',
    tag: 'UK',
    captain: 'Diego_UK',
    membersCount: 25,
    description: 'Caballeros urbanos listos para conquistar la escena de Clubes Pro.',
    bannerUrl: '/images/games-background/eafc.jpg',
    logoUrl: '/uploads/equipos/gMqJCYIpWm5iWGjSP3Dc_1783646342.webp',
    logoText: 'UK',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Liga Div 1',
    palmares: '2 Títulos',
    color: '#3B82F6',
  },
  {
    id: 'team-rangers-esports',
    name: 'RANGERS ESPØRTS',
    tag: 'RNG',
    captain: 'Alexis_RNG',
    membersCount: 24,
    description: 'Rangers eSports, identidad piducana en el fútbol virtual.',
    bannerUrl: '/uploads/equipos/bRlGeb6iuNldF9Y7WnrW_1783647699.webp',
    logoUrl: '/uploads/equipos/dWHCWagRiMjRWg2eIqQi_1783647689.webp',
    logoText: 'RNG',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Liga Ascenso',
    palmares: 'Sin Títulos',
    color: '#DC2626',
  },
  {
    id: 'team-puerto-montt',
    name: 'DEPORTES PUERTO MONTT ESPORTS',
    tag: 'DPM',
    captain: 'PtoMontt_Lead',
    membersCount: 30,
    description: 'Los hijos del temporal compitiendo al más alto nivel nacional.',
    bannerUrl: '/uploads/equipos/LEuqxyBR9TmMxuBOLXcA_1784039307.webp',
    logoUrl: '/uploads/equipos/RcUqiCRz65Gep5KoPX8q_1784039289.webp',
    logoText: 'DPM',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Liga Div 1',
    palmares: '1 Título',
    color: '#2563EB',
  },
  {
    id: 'team-chanchitos',
    name: 'FC CHANCHITOS',
    tag: 'FCCH',
    captain: 'Chanchi_Cap',
    membersCount: 20,
    description: 'Club carismático y temible en los mano a mano de Copa.',
    bannerUrl: '/uploads/equipos/EdInCEVK2vJv5WJaNIQF_1783801799.webp',
    logoUrl: '/uploads/equipos/qaCh0ZjbQ7qJdezkJaPZ_1783801784.webp',
    logoText: 'FCCH',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Copa Apertura',
    palmares: 'Sin Títulos',
    color: '#EC4899',
  },
  {
    id: 'team-tropiconce',
    name: 'TROPICONCE CF',
    tag: 'TCC',
    captain: 'Tropi_Lead',
    membersCount: 22,
    description: 'Fútbol de toque, ritmo y pasión penquista.',
    bannerUrl: '/images/games-background/eafc.jpg',
    logoUrl: '/uploads/equipos/NwqNYJTtvsmaxiTJ8fNA_1784047544.webp',
    logoText: 'TCC',
    platform: 'CROSSPLAY',
    status: 'ACTIVO',
    disputando: 'Liga Ascenso',
    palmares: 'Sin Títulos',
    color: '#F59E0B',
  },
];
