
-- -----------------------------------------------------------------------------
-- 26. COLUMNAS ADICIONALES (MIGRACIONES)
-- -----------------------------------------------------------------------------
ALTER TABLE games ADD COLUMN IF NOT EXISTS stats_schema JSONB NULL;
ALTER TABLE games ADD COLUMN IF NOT EXISTS ui_config JSONB NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS foto TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banner_url TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS biografia TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS country TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS instagram TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS facebook TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitch TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS youtube TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tiktok TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS discord TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitter TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS website TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS whatsapp TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS game_profiles JSONB NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banned_at TIMESTAMPTZ NULL;

ALTER TABLE organizations ADD COLUMN IF NOT EXISTS founded_year TEXT NULL;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS rating DECIMAL(3,2) NOT NULL DEFAULT 4.95;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS website TEXT NULL;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS redes_sociales JSONB NULL;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'Activo';

ALTER TABLE teams ADD COLUMN IF NOT EXISTS redes_sociales JSONB NULL;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS encargados_json JSONB NULL;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS banned_at TIMESTAMPTZ NULL;

ALTER TABLE competitions ADD COLUMN IF NOT EXISTS format TEXT NULL;
ALTER TABLE competitions ADD COLUMN IF NOT EXISTS match_mode TEXT NOT NULL DEFAULT 'PartidoUnico';
ALTER TABLE competitions ADD COLUMN IF NOT EXISTS group_count INT NULL;
ALTER TABLE competitions ADD COLUMN IF NOT EXISTS qualifiers_per_group INT NULL;

ALTER TABLE team_members ADD COLUMN IF NOT EXISTS organization_name TEXT NULL;
ALTER TABLE team_members DROP CONSTRAINT IF EXISTS team_members_role_in_team_check;

ALTER TABLE matches ADD COLUMN IF NOT EXISTS round INT NULL;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS home_team_tag TEXT NULL;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS away_team_tag TEXT NULL;

